### PR TITLE
Add support for additional mime-types.

### LINKED ISSUE #749: Video content is not being served.
Hello, 

I'm trying to include a video on a static HTML page.
The videos (*.mp4 and *.webm) are currently not playing and I believe that is because the mime types are not set by Suave.

https://github.com/fsprojects/FSharp.Formatting/blob/f389c0df2355412286b7a05a4aa86992f878b46d/src/fsdocs-tool/BuildCommand.fs#L630-L649

https://github.com/SuaveIO/suave/blob/57d69e39e67a5b1a1c60b7c015c698a1901a9420/src/Suave/Combinators.fs#L90-L114

The Suave docs explain how to add an additional mime type: https://suave.io/files.html

Can I include some more mime types? Hardcoded or via settings?

### PR DESCRIPTION
**Pull request by nojaf**
Fixes #749.

### CODE REVIEW

**Comment by baronfel** [comment]
this is a good escape hatch, but should the default set of MIME times be expanded? `.mp4` is pretty common these days

**Comment by nojaf** [comment]
Perhaps, but that begs the question should it be done here or in Suave itself?

**Comment by baronfel** [comment]
I think it could be a two-pronged approach - fix here as an intermediate, and provide the same fix upstream to Suave to let them decide if they want to take it.

**Comment by nojaf** [comment]
Sounds reasonable, I would need the escape hatch for the more obscure stuff in my project.

**Comment by nojaf** [comment]
@dsyme
, @eiriktsarpalis how do you want to see this fixed?

**Comment by dsyme** [comment]
> how do you want to see this fixed?

I think expanding the list here to include all the entries from ASP.NET Core makes sense, and then also contributing that to Suave.

**Comment by nojaf** [comment]
Closing in favour of #752.

**Pull request closed without merging**
