### PR TITLE
Get weights for roboto mono

### LINKED ISSUE #850: Some displayed examples may have broken indendation
Hi, the example here (List.concat) is seemingly not working, however this is due to messed up indentation. The source looks correct, so it's likely an issue with the rendering. 

billede

### PR DESCRIPTION
**Pull request by nhirschey**
It looks like firefox works if I explicitly request fonts with weights used in code snippets. Fixes #850 and fixes https://github.com/dotnet/fsharp/issues/16072

Screenshot of correct spacing in firefox with 600 weight (albeit with an aged local version of fsharp-core-docs):

image

### CODE REVIEW

**Review by nojaf — COMMENTED** [review]
Thanks for looking into this!
It looks good but we are hitting https://github.com/dotnet/fsharp/issues/16014 in the main branch.

Removing https://github.com/fsprojects/FSharp.Formatting/blob/27cb3f2cd5eb747285d658e12d44cba00e17faaa/global.json#L4 might make CI play ball again.

**Comment by nhirschey** [comment]
@nojaf I also added quotes to build.fsx so that it would work with spaces in the build path (dotnet fsi build.fsx used to fail on my PC).

**Comment by nojaf** [comment]
Thanks, I'm afraid the `rollforward` trick didn't work and as a workaround, we will need to remove all the lock files. 

Aslo removing
https://github.com/fsprojects/FSharp.Formatting/blob/27cb3f2cd5eb747285d658e12d44cba00e17faaa/Directory.Packages.props#L4

**Review by nojaf — APPROVED** [review]
Thank you!

**Comment by aski-codes** [comment]
Looks good here, thanks so much!

**Pull request merged**
