### PR TITLE
Format

### PR DESCRIPTION
**Pull request by nojaf**
Hi @dsyme, `fantomas-tool` was renamed to `fantomas` so you didn't bump to the latest version.

### CODE REVIEW

**Comment by dsyme** [comment]
> Hi @dsyme, fantomas-tool was renamed to fantomas so you didn't bump to the latest version.

I see!!!!  No wonder I hadn't seen the latest versions :)

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
Thank you!!

**Comment by nhirschey** [comment]
Were the deletions of `// FSX` and `// IPYNB` from `#end // FSX` conditionals intended? If I leave off `// FSX` then  the `#end` is left in the output .fsx file.

For example:
```fsharp
(***condition:fsx***)
#if FSX
let a = 4
#endif
```
results in an output .fsx with:
```fsharp
let a = 4
#endif
```


Is this from fantomas?

**Comment by nojaf** [comment]
Fantomas does appear not to restore the comment after a hash directive.
[Sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKBiAlgMzAMQHkCAdAJ2IDsAKASjMvUQvhzAHo38BlADUgBpwUAM6IALmMwUA5sNRgA2kIigIaqABIxATwAOyNJCliBytZA0A3AIYAbAK4HFZ9QAZB69ZACSzJmK5MAC9kD08IABYXMABdMwBfMJVoix19eSMKEyTzKztHeSVwiABGHK8AWWsADwAZKURapmkxAAtTYrASgCZXaLj1RLNVT1S9J0gmeAJseopELh1bUJS8hyci4u7y8wBRZhm5lc7IW2xIfoScka8tcYyAI1hYWw7RtYK0TfCAZh2IHwUUSkMR4KR2AByiAA7rYGm9wmJSI5LoNrqs0hMni8EbkbOtCtFIv8oFxdNZoIgAEKIbCwUiIAAK1lI1gAtuJEKRceokSjwgM1EN1DdcpjHs9XjsLPjPs5OgBWEmQMkU6m0%2BmNWDQrnQayiXyWWB6ySwCg8tR8xCooXo8JjdKGbFS1ayjZEsAANmVqspNLpDIAqrp9KQ9QaKEaTZgzRaINg7KIbRBhWpRQC7o6oM6LTL8u7OgB2H3kv0ahkAYVs%2BuEFbNwj50DE9LjYATtiTAquwwx9ydktzHwLxQAHCW1f7NRVEGyHlzW%2B3O55BSm7e9xf2cdKh4TOgBOcdlgOIOu2WMkxfWrtonv2zNYgfbt274oldwelWlxAAQWwYi5dZsmy1itlayZgKmyR3hu2aPq6%2BYvuEJRlB%2BvrqseXAzpgcBnuaF6Jley7diKvZZpAOZPghXwej0h4-n%2BXKYWy2EvOeHpgdetq3uufawVu8EEtRnQlH8qFft%2BpCwPYzAACKIHCzH-tyJIcURN4kdBvGZNkAlyt8nglBEypVNU3jYAAKq0TC7B2CytPSYgAOqYPAbSthEfScau3G3DB2mDs%2BQmvkqH4mb42CYNUBChtYzakLs1S6AywjCDGeEegqnlqVxGk8WRxgBVR8qvt6oU1AASogcCkPAzmue0JIeeBkFgOmmh%2BQVlGCcVSHFmV1SVdV8AQvYs5cjM3j-mycgkiUzVrr5WlsvYtiSHC8x4PSwESFy5n3F1ek0WOH6DfS8AVCta0NJtpDbUprYwK0LIUkpAD60IuW580%2BWKWmdbpw5IQe-USay2gEKQ9QNnVbmNVl6grhBC2-flWSFd1%2BnqL0xk1KD1jg5DmANiNY2kBNU0zTR325YtZHLatmDrYgN13bt%2B0A4hnjdChJx4wTUNiBdDNMyzsX3cq0BPayTZcu9n3tNTaakRM-13oFPVc9s-UAGr5lSUgsDIMMNR6I7w2oiMtW1Doq2jB2A1zoknCZeDSU2aX68wUjSMb7nmxAlvIxmHV2xzQXhN0Rn9TJsBiAA4uICVJYgKVpb7JKZYrUF5Q%2B-Fq0VmNqN0IXO5djMNFSZ7QAA1lS0vV%2BIwgEBQXDsieLyjelnSXlnrXKxKefvOrhcQN0pUnFCsIV%2BIOpMHt%2BhyRFFCYKaFDfsw06k5T3cEb31v3gPLr5xjHrdH1vNwtIFCuxQ7tmoEV%2BxfYDLmbAvhIFksVpQuu9eUjP3By0hRMOGssbHQvkpCgX9LBahkJvOcpBF5SBXmlbexQe5-ytv3TcR8h4F1PsDUuDMji1HZA8eA1gqywFSjISeTMf62T3tgviuDbjDw9D8d8Jwk5ckwByT%2BtgADSiBEC6Hfv4XwddrC3xNjvRhmCg7tSAXBY%2Bh1Og-B5sUSAldpHVyOMICSUlmBQgbIgc6ZcmZJ2SqlesoFkSEQRsRJWmkyLANUQ7dQPwtYnCpCyScDIZJE2gKQPh4J-zwEDMvM0cloDVlZKvBhS5HHqWcTnQ%2B6M1HFB%2BE7LRPCQn8LEHYRYkl7ANmRLoRY2hliJIcRbJx2daa2x0u4zmnio4nGEaIkyJMEEzB0RQPRDQ0FIVcP7WI9S%2B4uNzqwvE%2BD1Ely0cU7CgsEDHHQb-bKKYhAxDCEYYQeBUryB7vEIAA).

**Comment by dsyme** [comment]
They weren't intended.  @nojaf Did you create a tracking issue for this in fantomas?

**Comment by dsyme** [comment]
Fixed for this repo via a .fantomasignore entry 

https://github.com/fsprojects/FSharp.Formatting/pull/751

**Comment by nojaf** [comment]
@dsyme, no I didn't. I'm a bit confused here, is this relevant or not?
If there is meaning to the comment after the hash directive, if can't help but feel that this solution should be reviewed instead.
Fixing this in Fantomas will introduce a messy solution. You want to assign a trivia to a trivia here.
This little manoeuvre won't be pretty and probably introduce a performance hit for everybody.
I'd like to know more before trying to address this on Fantomas' side.
This feels very unorthodox, to be frank.

**Comment by dsyme** [comment]
Hmmm, I suspect it's quite common to have clarifying comments in this position, I know I do it all the time. We should probably open a fantomas issue and discuss there. 

In this case yes, there's a meaning of sorts for the tool processing the scripts (that could be implemented ways)

**Comment by nojaf** [comment]
This will be painful if we need to check this in larger files: [example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPAjGALxiED0ZYcAttYgHZYA6ATk-ZjrgEzFi8UqsWg2ZsO2PAGY%2BMwTTqNW7TngAsfDfOGKxKybgCsfY9pFLxq3ADY%2Bts7uUSuAdj5uHop1YAcfP54W%2BlwAnHxhgXrOePgADHxxYJHeBviEJGlJlApelqm8GQLZOrnBMTIZcsXmUVb4Ghla1Y55XPjGGabNpdEEthn23UG9%2BG4ZHkO1qX4ZAZMpbWEZEfOteNzxJBtZQjUL6%2Bn85KtlPAX8Rbstp9wV-FVXPVbcDfxNj8PPHfxdH1Nc3H6-EGf32PDG-AmoLWPBm-Dm0JuS34K0RvSkmzAGJ2OU%2BBikhwJOJKeK4UnO5OJexhUjutKp13Rryk71x-2k3ykvzZYKkQL5DKe%2BIhUihPJpcKkCPFpykyLlgtJ6kxaniyRhakOmsV7NwanO%2Bp1YLUdxNRo1rzUrJJurU3zt5tOaiBzsdvTUEI9bqsajhvu9BjUyKDAa4hkx4dDeEMhxjUaM50MlxlvUMdzT8cMryzme%2Bhm5NrBhiBxczEMMYsLMMMcJrmeRhlRKas1kxrfj1kOnY752syarp2sdyHHde1mt1MH32sBcnvWsQIXHYh1krc5bcOs0oH8%2BR1ibO6sLkxx-jLkO57P5xc-fXBhcdwfZ9eLgnjKP3xcs-f96BLhBzb3hCLhrj%2Brhwi4253q4yIuAe0F4D4mJIfGPiHGhqHnD4t5gYhdw%2BA8gFcD4rwkah3w%2BN%2BQrEUCPgAYeBg%2BBCTGoXCPhQbhuA%2BMi3HxiEmL8XxhwhMcaJWCE5wSXxdwhIRDGhK8IRvtReAhN8al8UCIT0QhuAhBC%2Bl8XCIQcSpenIiE8GcXEmI2W6TgAMQAJYAGZgAAYgA8p5jkMPArk7H5HneZAAA04BQAAztgWBOfQADmkWoGAADaEUQKAEBZVAAAkWAAJ4AA7IGgkBxVgYXpVlkA5QAbgAhugACuJWpVV2WxOF2XZZAACS9BIIwADKTkAF7IF13UQGo7VgAAulVAC%2Bk0ZbNNUFcVyVlYwlVTTVDXNa1aVTRA%2BArd1kAALL1bgAAycWILdDDxVgAAWu0nfgGyzQt2XLVVmUXXlRWtZAfmeS5930IgQ0FZgH09XVjUtclx0ndw509QAogNENQxNs0QJA6AuZAP1LedgOIxtoMAEawLA6AI9VSOHajhNYpj1X9dFLBYO5cWNQAcogADu6APcz2VYCwLXk39lNrcDm2lfTjNS7lB0o2gaNTWoXNE0NhX1dAiAAEKIC5sAsIgAAK9UsPVdBYIgLAaxAMty1Nv1Zf92VUyzNNbWrTNc-tyNHRzhgG1ARsm%2BblvW49sCi670D1dF-W1bA6exbA9Du2AnuIPLvuK3tyt0wzodK1rkcnWA1gx5AcemxbVs2wAqoVxUsOnmf0NnudOfnhcuY10WlxAftZQHROV8H1ca%2BHbM6xzLjN63Ccd4gADC6AZ5Fu-55FnvQFg1tjxPJfexTANK0HqtL2HrPa21Dc%2BJvxtt4nNuXYg1BaauyvugSet8Fb3wro-KAIdl6v3ridEIX947tyTsfdAo8Y7j1ATfbqPtp7lyBtAyAsCX513Zg3OIyDTYAEEXIuxYMfWg9VC7FynmAGeq0oEg0XurMhEcKGfTOhzFu39t5JyGgApycAMEFywdfdhnCwBz1ysQ0htcBFr0oRjERW86EMMkdQaRjNMEczYeAsukCiE8KfnwjRq936fSkNQxANCWCwCagNAAIogCWRiGGsNlrg7K%2BCOGEOpjYqA5U4HkK0Z9fWIjrq4F6i5AAKq9BgWMcFDVetbLAAB1Jy8A3qF1VIo8JgdInbQqvwhxuturtGbkk-qLknK4E8r3eqF8WBY1wIVG2kVIojzkVHWI5SrERJVlEnatS371OyvgJuiSboACVEBwBYPAQpxT3oxzKRYghEzKlTOqTEzRjipqjCaas9Z1t4BCyaoA12ENeou2oElGO%2BBxn%2BwflU6gTV0CxQltDdy1tqBdIYaknhsyEGXM-iItZGz4CXQBUCh6oKWDgqwAE5u0BXoOxNgwgA%2BqLIpJTvmz1%2BSc6JMLBGXKQcs3AbjHb5U8iwe6p9tklL2WMg5YSjnz2ITS%2BxcyOYbGuUylgLK2UcqwA8p5LAXlvI%2BRzL5fKlEqPWn81FTlgWIAxViyF0KRWwu6twYRDdIDMvqqy9lTlT4osBbq9FYKIXANxfix259XYkrJe9ClXDrHUpmSaulZqdGWqSQANQjmbOK-kEpct2RzJCAblFUtBsKiusSLlmucYy9ynjz7DLjQNOK8Uk2lN5Xgu%2BPzuHBpqaGuJU0XgSq8bALAABxbAvT%2BmIEGcMytMdwxps1QvWxNds3nPmVlbg0dEk6r1WbDB0AADWZsvWruwJFTy9AhpOz3ozR5IyG7YLATWiBdag1VzsVOupYqlmWpFuLB6FssCpwYFC4qPjWn0CcnnegNCBr-wVSq09Cj1UVMFVU9Rd7RUN24BvERNCJbxXoIW%2Bgxb84jTQ10pqNtUmwH6oNLAXThkgPPSE2tlL603snUDHNM6IDcHhZalDDD6BkdqsnBKIGgEsB-XFf9wywMnTPcErKoSNUZt4fRxGjGxUMsjTq-Gt0na03gPVfesAhkJWfXqijEmIBSag6omDz8m25uyhiZuvbXZOV0I1AA0ogRAhViOiH6hu%2BqmHk3gZwaOmTE6zn3obgSZuy6fOrvxpFNxHiBoi1PogZFi6Hq9oGUMk%2BgSvYXssVeyZdGQvwZOuSCLDtUE2y8fa6ALAHOCxdvATuf784%2BOgAfR2AHDOBdo7JorprrP5stXZ2rjn0Cw3cU1U%2BstCqw3yvDeRAXIMCrMw2vrYbrMJMtS5tzST5X8YhpF%2Bg0WHqicubEatVHL00evb12lzbupck3jLaRWBLoIAJv5yjkmloRTmpNMqkV3JDOSuJkAi0gA).

Every comment after source code that is not yet assigned should be checked against hash directives.
This feels like it should be an IDE hint feature instead.
I'm open to discussing this further on Fantomas' side.

**Pull request merged**
