### PR TITLE
Specify VisualStudioVersion so it finds Microsoft.FSharp.targets

### PR DESCRIPTION
**Pull request by conniey**
This fixes the "The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length." error because it cannot locate Microsoft.FSharp.targets.
The root cause appears to be that the [VisualStudioVersion is not being set at the appropriate level](https://stackoverflow.com/questions/38343130/error-msb4102-the-value-of-the-project-attribute-in-element-import-is-in)

I copied the contents from: [FSharp.CodeFormat.fsproj#L37-L66](https://github.com/fsprojects/FSharp.Formatting/blob/master/src/FSharp.CodeFormat/FSharp.CodeFormat.fsproj#L37-L66) to set the VS version to 2015.

/cc: @matthid

### CODE REVIEW

**Comment by matthid** [comment]
Yes that works, in other repros we used the fsharp.compiler.tools package.
I thought we were already using it here as well (and was a bit puzzled on your error report).
This should work as well, thanks!

**Comment by conniey** [comment]
@matthid Based on your feedback, I modified each project to use FSharp.Compiler.Tools instead. Does this work better?

**Comment by matthid** [comment]
The build is failing because one project uses nuget for some reason... It should work when migrating it to paket (ie packages.config -> paket.references -> paket install, maybe some manual cleanup of the fsproj)

Thanks! Let me know if you run into trouble.

**Comment by conniey** [comment]
I fixed it now.. and both builds appears to be passing. :)

**Comment by conniey** [comment]
@matthid Hey, does this work for you?

**Comment by matthid** [comment]
Yes absolutely, sorry :)

**Pull request merged**
