### PR TITLE
Adding markdown with a bit of info about how to upgrade

### PR DESCRIPTION
**Pull request by wallymathieu**
Open question:

- [x] Where should this information be linked from?

I've used feedback from @jackfoxy on what should be part of such a upgrade path https://github.com/fsprojects/FSharp.Formatting/issues/453

### CODE REVIEW

**Comment by matthid** [comment]
I guess one location would be the release notes. We could add that link for every beta until we do the release.

**Comment by jackfoxy** [comment]
The current upgrade link in release notes 404 http://fsprojects.github.io/FSharp.Formatting/upgrade_from_v2_to_v3.html

**Comment by wallymathieu** [comment]
Thanks @jackfoxy !

**Comment by wallymathieu** [comment]
@matthid do we need to generate the documentation from the v2 branch (in order to avoid docs from v3 to be shown)?

**Comment by matthid** [comment]
Good question... We have no general solution to that problem ...

**Comment by wallymathieu** [comment]
I can cherry pick d35fb84651e0eee3469f879d7792bcda43b5b4bf to the v2 branch in order to regenerate docs

**Comment by matthid** [comment]
Honestly, I'm OK either way (ie generating docs from v3 or cherry picking into v2).

**Comment by wallymathieu** [comment]
I've tried regenerating the docs, and it looks like it gets further when I start on #460, I'll try to diagnose what goes wrong

**Pull request merged**
