### PR TITLE
Fix arguments naming and escape operator name in usageHtml

### PR DESCRIPTION
**Pull request by DedSec256**
Some operator names are displayed incorrectly due to missing escaping; also, the argument names are duplicated.
This PR fixes that.

Before:
https://github.com/dotnet/fsharp/blob/0063f20f6cd49d016d5d234b9c1b7df00c2e9a4d/src/FSharp.Core/Nullable.fsi#L173
image
image

After:
image

- [x] Tests

cc @BoundedChenn31

### CODE REVIEW

**Comment by dsyme** [comment]
Looks good. Will you add tests?  I'm OK with taking as is.

**Comment by DedSec256** [comment]
@dsyme, yes, we would like to add some tests for it in the near future.

**Review by BoundedChenn31 — APPROVED** [review]

**Comment by DedSec256** [comment]
@dsyme, we think it's ready

**Review by dsyme — APPROVED** [review]

**Comment by dsyme** [comment]
You probably want to exclude these from code formatting, or else format them

```
tests/FSharp.ApiDocs.Tests/files/FsLib1/OperatorsWithFsi.fsi needs formatting
tests/FSharp.ApiDocs.Tests/files/FsLib1/OperatorsWithFsi.fs needs formatting
```

**Comment by DedSec256** [comment]
@dsyme, it could be merged I think (:

**Comment by dsyme** [comment]
Thanks!

**Pull request merged**
