### PR TITLE
add minimal seo tags for open graph and twitter cards to default template

### PR DESCRIPTION
**Pull request by kMutagene**
see #869 

This is a basic implementation using the available substitution parameters. There could be more, e.g. displaying a default image etc., but i think for that we would need additional substitutions.

### CODE REVIEW

**Comment by Thorium** [comment]
Is there something good that could be added to the meta description tag?

**Comment by nojaf** [comment]
Maybe we can use the `<Description>` tag from the cracked projects?

**Comment by kMutagene** [comment]
> Maybe we can use the [Description](https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild#add-an-optional-description-field) tag from the cracked projects?

I was thinking about that, but this has the same problem as `fsdocs-authors` has - if the respective xml tag in the cracked project does not exist, the tag will contain rubbish. However i agree that that tag would be a sensible default when it exists.

**Comment by nojaf** [comment]
We could also fix that part. Having better defaults or use empty strings if not replaced. Or let the tool crash in a strict mode if values are missing.

**Pull request merged**
