### PR TITLE
Update to dotnet 7.

### PR DESCRIPTION
**Pull request by nojaf**
I was able to generate the Fantomas API docs locally with this change.
//cc @dsyme

### CODE REVIEW

**Comment by nojaf** [comment]
At one point I did see this error on my local machine:
```
/home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.Common/YaafFSharpScripting.fs:line 144
   at FSharp.Formatting.CodeFormat.CodeFormatter.processSourceCode@345-1.Invoke(StringReader reader) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/src/FSharp.Formatting.CodeFormat/CodeFormatAgent.fs:line 363
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 510
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
--- End of stack trace from previous location ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 454
   at Microsoft.FSharp.Control.AsyncPrimitives.QueueAsyncAndWaitForResultSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1140
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1167
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 1511
   at FSharp.CodeFormat.Tests.getContentAndToolTip(String source) in /home/runner/work/FSharp.Formatting/FSharp.Formatting/tests/FSharp.CodeFormat.Tests/CodeFormatTests.fs:line 124
   at FSharp.CodeFormat.Tests.getContent@129.Invoke(String x)
   at FSharp.CodeFormat.Tests.Functions and methods are in spans of 'f' class() in /home/runner/work/FSharp.Formatting/FSharp.Formatting/tests/FSharp.CodeFormat.Tests/CodeFormatTests.fs:line 207
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Failed Functions and methods are in spans of 'f' class - custom CSS [3 ms]
  Error Message:
   System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

it is trying to use the legacy resolver for some reason.
Then it went away, but I assume the problem is still there.
Do we need a change for `fsChecker.GetProjectOptionsFromScript`?

**Comment by nojaf** [comment]
I'm not going to claim I fully understand how this works but if you target `net6.0` the MSBuild DLLs are not published to the output folder. Using `net7.0` they are and the test pass.

The next bottleneck would be getting FAKE to work on `net7`. (See https://github.com/fsprojects/FAKE/issues/2719)

**Comment by nojaf** [comment]
Hello @dsyme, would it be ok if we changed the FAKE script to a project instead?
See [docs](https://fake.build/guide/getting-started.html#Run-FAKE-using-a-dedicated-build-project).
It would resolve the current `net7` problem.

**Comment by dsyme** [comment]
@nojaf Thanks! this is great

Even better would be to remove the use of FAKE from this core project.

**Pull request merged**
