### PR TITLE
Fixing issue Unit returning functions yield warning #936

### PR DESCRIPTION
**Pull request by MatthijsPrent**
PR to fix issue #936

### CODE REVIEW

**Comment by nojaf** [comment]
Hello, thank you for this contribution.
Please run `dotnet fantomas build.fsx src tests docs` to format your changes.

**Review by nojaf — APPROVED** [review]
LGTM! Do you want a release for this? Best I can do there is another alpha.

**Comment by MatthijsPrent** [comment]
Thank you! For us a new release for this is not urgent. If another (alpha/beta) release will appear within +-3 months that is fine with me.

**Comment by nojaf** [comment]
Gotcha, I would expect that to happen in that time frame. Poke me if not.

**Pull request merged**
