### PR TITLE
Relative paths in html

### PR DESCRIPTION
**Pull request by nojaf**
Fixes https://github.com/fsprojects/FSharp.Formatting/issues/769

### CODE REVIEW

**Comment by dsyme** [comment]
Hmm failing tests:
```
  Failed Substitutions apply to correct parts of inputs [54 ms]
  Error Message:
   System.Exception : "substitute-in-fsx-code: simple1" is not a substring of "<!DOCTYPE html>
```

**Comment by nojaf** [comment]
@dsyme found the problem!

**Comment by nojaf** [comment]
Well hello, [fellow maintainers](https://github.com/fsprojects/FSharp.Formatting#maintainers), @baronfel and @nhirschey, is this one ok for you folks?

**Review by baronfel — APPROVED** [review]
LGTM!

**Pull request merged**
