### PR TITLE
packages update

### PR DESCRIPTION
**Pull request by dsyme**
A packages update and removes dependency on System.ValueTuple now FCS doesn't require it

### CODE REVIEW

**Comment by kurtschelfthout** [comment]
Bump.

**Comment by matthid** [comment]
Oh, somehow I did miss this one. I think the URL changes are still relevant, the rest are only updates by paket, correct?

**Comment by kurtschelfthout** [comment]
Yes, it looks like it - changes in fs files for the URLs and one in build.fsx to remove dep on ValueTuple.  Other stuff is hopefully just the result of `paket update`.

I think there's also some manual changes to AssemblyInfos that should probably be driven from the release notes version instead in this PR.

**Comment by matthid** [comment]
Yes `AssemblyInfos` are automatically generated by FAKE. I'd love to see an update for this. Sorry for my total failure and missing it.

**Comment by matthid** [comment]
@kurtschelfthout Could you help out?

**Comment by kurtschelfthout** [comment]
I'll try later, but not right now :). I tried using this package from the appveyor build to see if it fixes things but didn't get it to work yet ;)

**Comment by kurtschelfthout** [comment]
Between the API changes in 3.0 and FSharp.Core and possibly all the rest of the netcore changes I have been unable to get this to work. It keeps telling me it's missing type `Attribute` or some such. Sigh.

I'm _really_ short on patience right now having just gone through all that with trying to get literally every other tool I use in FsCheck so I'm bowing out here. Sorry, it's not your fault but it makes me really grumpy.

**Comment by matthid** [comment]
It probably IS my fault as I introduced the breaking API change:
 - NEW: https://github.com/fsharp/FAKE/blob/master/help/markdown/dotnet-assemblyinfo.md
 - OLD: https://github.com/fsharp/FAKE/blob/master/help/markdown/legacy-assemblyinfo.md

Sorry for that.

Yes I'll take a look eventually, but this repository is quite low on my priority list at the moment (there is just too much other stuff)

**Comment by kurtschelfthout** [comment]
No worries, no one has complained about the lack of tooltips in the docs yet ;)

**Comment by realvictorprm** [comment]
Still valid?

**Comment by matthid** [comment]
We merged the relevant changes, thanks to @wallymathieu

**Pull request closed without merging**
