### PR TITLE
Add upper border to FCS dependency

### PR DESCRIPTION
**Pull request by kMutagene**
See @baronfel 's suggestion at #511 .

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
One thing to note is that, last time I checked, version ranges in paket.dependencies are not reflected in nuget packages, so this will have no effect on the generated artifact.

**Comment by eiriktsarpalis** [comment]
I did in fact verify that this is the case by checking the [generated artifacts in AppVeyor](https://ci.appveyor.com/project/matthid/fsharp-formatting-32np3/builds/32407387/artifacts).

**Comment by baronfel** [comment]
Good eye @eiriktsarpalis, it looks like the paket `fix-nuspecs` command, which is used to plug in to the dotnet sdk build pipeline, hasn't learned how to adjust version ranges that were generated by the SDK nuspec generate tasks.  It looks like the fix would need to be in this traversal function: https://github.com/fsprojects/Paket/blob/1ab743a5a928146059842ad7f35cc8501769ff80/src/Paket.Core/PublicAPI.fs#L878

**Comment by kMutagene** [comment]
Yeah I missed that, i just expected the pack command to add the version constraints. @eiriktsarpalis  you seemed to have fixed #511 in #514 i will close this.

**Pull request closed without merging**
