### PR TITLE
Remove binder badge/link

### PR DESCRIPTION
**Pull request by cartermp**
fixes https://github.com/fsprojects/FSharp.Formatting/issues/567

### CODE REVIEW

**Comment by cartermp** [comment]
Looks like some windows/unix diff nonsense, with this you can see it's just removing the binder link: https://github.com/fsprojects/FSharp.Formatting/pull/572/files?diff=split&w=1

**Comment by dsyme** [comment]
You should fix it in the source documentation in master instead please :-)

**Comment by dsyme** [comment]
Docs will get rebuilt on release, currently not automated here

**Comment by cartermp** [comment]
oof, more complicated. will close and do it a different way

**Pull request closed without merging**
