### PR TITLE
add bottom margin to included code output

### PR DESCRIPTION
**Pull request by nhirschey**
Addresses issue raised here https://github.com/fsprojects/FSharp.Formatting/issues/686

### CODE REVIEW

**Comment by dsyme** [comment]
Thanks!

**Comment by dsyme** [comment]
@nhirschey I think @gbaydin has recently made some more improvements to DiffSharp CSS, we should trial them for incorporation back into here

**Comment by gbaydin** [comment]
I can send a quick PR with the latest one I'm quite happy with.

**Comment by dsyme** [comment]
Yes please do if you have time, @nhirschey if you could review, trial and compare that would be great

@gbaydin please copy back any recent changes line by line rather than wholesale, the CSS wasn't completely aligned

**Comment by nhirschey** [comment]
Sure, I'm happy to review and compare. I like the diffsharp style. So far this is the only style "regression" that I noticed.

**Pull request merged**
