### PR TITLE
Fix generate.fsx link

### PR DESCRIPTION
**Pull request by marcpiechura**

### CODE REVIEW

**Comment by wallymathieu** [comment]
This looks simple enough

**Comment by wallymathieu** [comment]
Perhaps it would be helpful with a bit more description in what you are fixing.

**Comment by marcpiechura** [comment]
The current link is broken, github shows the 404 page. This PR fixes the link so that you see the actual generate.fsc file 😉

**Comment by matthid** [comment]
Yes thanks!

**Pull request merged**
