### PR TITLE
Update FSharp.Compiler.Service to 43.7.200

### PR DESCRIPTION
**Pull request by nojaf**
A naive attempt to update FCS.

### CODE REVIEW

**Comment by nojaf** [comment]
A couple of tests seem to fail. Altough not if you run them in isolation.

**Comment by nojaf** [comment]
For some reason the evaluation of `"it"` stops working after a while:
image

**Comment by nojaf** [comment]
This would resolve https://github.com/fsprojects/FSharp.Formatting/issues/799 as well.

**Comment by nojaf** [comment]
I tried this locally and this does appear to work for me.

**Review by baronfel — APPROVED** [review]
This is without a doubt the most beautiful, efficient, and effective code I have ever seen.

**Pull request merged**
