### PR TITLE
Retry project cracking when there isn't a targetPath

### PR DESCRIPTION
**Pull request by wallymathieu**
- This pull request is supposed to fix the issue #574

I've based the logic on this comment:
https://github.com/alfonsogarciacaro/TypeProviderTest/blob/4cb6442afce6db707e56a1a43c79d3cc7cd4211a/ASTViewer/ProjectCoreCracker.fs#L111-L114
```
      // As workaround, lets choose the first of the target frameworks and use that
```

### CODE REVIEW

**Comment by dsyme** [comment]
Fix conflicts with master please?

**Comment by wallymathieu** [comment]
Will do.

**Comment by wallymathieu** [comment]
How does it look now @dsyme ?

**Comment by dsyme** [comment]
big conflict here, with #618 , my apologies

**Comment by dsyme** [comment]
> big conflict here, with #618 , my apologies

I should have prioritised this one since you've already fixed conflicts one :-(

**Comment by wallymathieu** [comment]
Does it look OK @teo-tsirpanis ?

**Comment by teo-tsirpanis** [comment]
Yes @wallymathieu, it seems OK to me.

BTW most of it will be rewritten anyway when ionide/dotnet-proj-info#87 is fixed.

**Comment by wallymathieu** [comment]
Sounds good. So then some of this can be removed once that happens 🙂?

**Comment by teo-tsirpanis** [comment]
Yep. But let's merge it for now...

**Comment by wallymathieu** [comment]
> > big conflict here, with #618 , my apologies
> 
> I should have prioritised this one since you've already fixed conflicts one :-(

The conflict was kind of small in the sense that it was mostly moved code.

**Comment by wallymathieu** [comment]
I'll merge it @dsyme later on today.

**Pull request merged**
