### PR TITLE
try to update to F# 6 and .NET 6

### PR DESCRIPTION
**Pull request by dsyme**
builds on #718 , tries to update FCS and .NET 6 but hits problems with MSBuild

### CODE REVIEW

**Comment by gbaydin** [comment]
Any news on dotnet 6 support?

**Comment by dsyme** [comment]
I'll check where we're at

**Comment by gbaydin** [comment]
I wanted to update DiffSharp to dotnet 6 here https://github.com/DiffSharp/DiffSharp/pull/395 but I couldn't merge it because fsdocs keeps failing

**Comment by dsyme** [comment]
Replaced by https://github.com/fsprojects/FSharp.Formatting/pull/738

**Pull request closed without merging**
