### PR TITLE
try apply fantomas formatting to entire codebase

### PR DESCRIPTION
**Pull request by dsyme**
Seeing how fantomas formatting fares for this codebase

cc @nojaf

### CODE REVIEW

**Comment by dsyme** [comment]
@tpetricek You might like to take a look at this, how Fantomas formats your old code (though this doesn't include some recent improvements to Fantomas)

It takes 2-space indent --> 4-space indent for example, and various other things.

**Comment by dsyme** [comment]
@nojaf Putting aside the small issues I reported in Fantomas repo, I'm really impressed that Fantomas can format this codebase and pass tests. 

The results are generally really good.  All the old 2-space indentation is gone, and although there's a significant code expansion it's somehow clearer and likely more maintainable.

**Comment by tpetricek** [comment]
It's really nice Fantomas can manage this! Of course I still like my 2 spaces ;-) but I'm perfectly happy for this to be merged. F# Formatting should adopt a style that works for the contributors, is easy to maintain and works well for people with more than a tiny laptop screen! So +1 from me.

**Comment by dsyme** [comment]
The most painful changes are ones like this, where test cases have expanded from 1 to ~50 lines, because the structured F# data for the expected output is much larger when formatted. I'm not quite sure what to make of that.

https://github.com/fsprojects/FSharp.Formatting/pull/716/files#diff-bbf18b4a9ffd612b7bce071e8d5e9137d82cf0686447dc2894cf5223ea82b711L364

**Comment by nojaf** [comment]
>  I'm really impressed that Fantomas can format this codebase and pass tests.

Thanks, I'm really happy how things have progressed over the years. Fantomas is really usable these days.
That being said, you have yet to encounter your first catastrophic failure @dsyme. Trust me, those are still present in certain files. If you happen to be confronted with those, I suggest you ignore the file in a [.fantomasignore](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore) or wait to format the repository until all problems are fixed.

**Comment by dsyme** [comment]
> That being said, you have yet to encounter your first catastrophic failure @dsyme. Trust me, those are still present in certain files. If you happen to be confronted with those, I suggest you ignore the file in a .fantomasignore or wait to format the repository until all problems are fixed.

Oh I found those! Reported them to fantomas

I didn't know about `.fantomasignore` - thanks

**Pull request merged**
