### PR TITLE
Pass `--multiemit-` as default option for FsiEvaluator.

### PR DESCRIPTION
**Pull request by nojaf**
After updating to v18 in Fantomas, we noticed that Linux is no longer processing `(*** include-output ***)`.

When locally (in WSL) adding `--multiemit-` to `FsiEvaluator` is started working again.
I propose we ship this out of the box.

Thoughts @baronfel?

### CODE REVIEW

**Comment by dsyme** [comment]
It would be good to understand what the problem is.  Any specifics?

It's ok to turn off multiemit (it's primarily for debug symbols) but I'd like to understand better what's failing.

**Comment by nojaf** [comment]
@dsyme it first surfaced during [the upgrade to FCS 43](https://github.com/fsprojects/FSharp.Formatting/pull/796).

Some `eval` calls would stop working after the second invocation.
It was a bit icky to troubleshoot, it would happen when you run two unit tests (from `FSharp.Literate.Tests.Eval`) sequentially.
Running either test individually would work, but the last test would fail after evaluation.

**Comment by nojaf** [comment]
We should definitely investigate this behaviour, but I'm going to merge this in for the time being as it does break certain use cases.

**Comment by nhirschey** [comment]
This didn’t bump the release. The nuget version is still 18.1.0

https://www.nuget.org/packages/FSharp.Formatting

**Pull request merged**
